<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generator" nsURI="com.hirain.tae.generator" nsPrefix="generator">
  <eClassifiers xsi:type="ecore:EClass" name="DynamicGuiActivity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeGuis" upperBound="-1"
        eType="#//AttributeGuiProperties" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeGuiProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attrView" lowerBound="1"
        eType="#//GuiControl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuiControl">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewType" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewExtend" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrDefaultValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrDescription" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrLabel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=" "/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=" "/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scriptName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationrule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicValueActivity" eSuperTypes="testcase.ecore#//DirectActivity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toolType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceInterfaceType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toolName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceInterfaceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputField" upperBound="-1"
        eType="#//FieldModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputField" upperBound="-1"
        eType="#//SaveAndAssertFieldModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeoption" eType="ecore:EClass testcase.ecore#//ExpectationTimeOption"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDynamicValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=" "/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attrValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationrule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldModel" eSuperTypes="#//AttributeDynamicValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="SaveAndAssertFieldModel" eSuperTypes="#//FieldModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="save" lowerBound="1" eType="ecore:EClass testcase.ecore#//IsSave"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taeAssert" lowerBound="1"
        eType="ecore:EClass testcase.ecore#//IsAssert" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
